=== NikolaPacaric2025270992/VISProjekat/NoviProjekat/Backend/VBIS_Projekat/src/main/resources/schemas/polaganje-schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Lista Polaganja",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "id": { "type": "string" },
      "studentId": { "type": "string" },
      "predmetId": { "type": "string" },
      "ocena": { 
        "type": "integer",
        "minimum": 5,
        "maximum": 10
      }
    },
    "required": ["studentId", "predmetId", "ocena"]
  }
}

=== NikolaPacaric2025270992/VISProjekat/NoviProjekat/polaganja-import.json
[
  {
    "id": "placeholder",
    "studentId": "placeholder_student",
    "predmetId": "predmet_it_uvod_java",
    "ocena": 8
  },
  {
    "id": "placeholder",
    "studentId": "placeholder_student",
    "predmetId": "predmet_it_arhitektura_racunara",
    "ocena": 10
  },
  {
    "id": "placeholder",
    "studentId": "placeholder_student",
    "predmetId": "predmet_it_mreze",
    "ocena": 7
  }
]
